#!/usr/bin/env python3
import argparse
import json
import getpass
import os
import platform
import shutil
import subprocess
from pathlib import Path


ENV_GROUPS = (
    ("Core: local search and indexing", (
        "FEATURE_LEVEL", "ZOTERO_DATA_DIR", "CHROMA_DIR", "EMB_PROFILE",
        "EMB_MODEL", "EMB_DEVICE", "HF_HUB_OFFLINE", "TRANSFORMERS_OFFLINE",
    )),
    ("Citation network and bibliographic metadata", (
        "S2_API_KEY", "ZOTERO_USER_ID", "ZOTERO_API_KEY", "CINII_APP_ID",
        "CROSSREF_MAILTO",
    )),
    ("LLM-assisted features", (
        "LLM_DEFAULT", "LLM_EXPAND", "LLM_SUMMARY", "LLM_EXTRACT",
        "DEEPSEEK_API_KEY", "DEEPSEEK_THINKING", "DEEPSEEK_REASONING_EFFORT",
        "ANTHROPIC_API_KEY", "LLM_OPENAI_BASE_URL", "LLM_OPENAI_API_KEY",
        "SUMMARY_EXCLUDE_TAGS", "EXTRACT_EXCLUDE_TAGS",
        "SUMMARY_ALLOW_CLOUD_ALL", "EXTRACT_ALLOW_CLOUD_ALL",
    )),
    ("Optional nightly automation", (
        "NIGHTLY_ENABLE", "NIGHTLY_START_TIME", "NIGHTLY_LAUNCH_MODE",
        "NIGHTLY_MAX_HOURS", "NIGHTLY_MAX_ITEMS",
        "NIGHTLY_MIN_WEEKLY_REMAINING_PERCENT", "NIGHTLY_STOP_FILE",
        "NIGHTLY_REOCR_ENABLE", "NIGHTLY_REOCR_CANDIDATES", "NIGHTLY_REOCR_MAX_ITEMS",
    )),
)


def read_env_file(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if "=" in stripped and not stripped.startswith("#"):
            key, value = stripped.split("=", 1)
            values[key.strip()] = value.strip()
    return values


def write_env_file(path: Path, values: dict[str, str]) -> None:
    """Write a predictable, grouped .env while preserving unknown settings."""
    rendered = [
        "# Generated by scripts/setup_wizard.py.",
        "# Secrets stay local: .env is excluded from Git.",
    ]
    written: set[str] = set()
    for title, keys in ENV_GROUPS:
        rows = [f"{key}={values[key]}" for key in keys if values.get(key, "") != ""]
        if rows:
            rendered.extend(["", f"# {title}", *rows])
            written.update(key for key in keys if values.get(key, "") != "")
    extras = sorted(
        key for key, value in values.items() if key not in written and value != ""
    )
    if extras:
        rendered.extend(["", "# Other existing settings"])
        rendered.extend(f"{key}={values[key]}" for key in extras)
    path.write_text("\n".join(rendered) + "\n", encoding="utf-8")


def _set_optional_secret(config: dict[str, str], key: str, prompt: str) -> None:
    current = bool(config.get(key))
    suffix = " [configured; Enter keeps it, '-' removes it]" if current else " [optional]"
    value = getpass.getpass(prompt + suffix + ": ").strip()
    if value == "-":
        config.pop(key, None)
    elif value:
        config[key] = value


def _set_required_secret(config: dict[str, str], key: str, prompt: str) -> None:
    """Require a secret while allowing Enter to retain an existing value."""
    while True:
        current = bool(config.get(key))
        suffix = " [configured; Enter keeps it]" if current else " [required]"
        value = getpass.getpass(prompt + suffix + ": ").strip()
        if value:
            config[key] = value
            return
        if current:
            return
        print(f"{key} is required for Citation Network. Please enter a key.")


def configure_feature_level(config: dict[str, str]) -> None:
    current_level = config.get("FEATURE_LEVEL", "core")
    default_choice = {"citation": "2", "llm": "3"}.get(current_level, "1")
    print("\n3. How far do you want to configure this installation?")
    print("   [1] Core local RAG — local embeddings, search, context, outlines")
    print("   [2] + Citation Network — Semantic Scholar/OpenAlex (internet + S2 key required)")
    print("   [3] + LLM automation — summaries, query expansion, reference extraction")
    choice = input(f"Select [1-3, default is {default_choice}]: ").strip() or default_choice
    level = {"2": "citation", "3": "llm"}.get(choice, "core")
    config["FEATURE_LEVEL"] = level

    if level in {"citation", "llm"}:
        print("\nA Semantic Scholar API key is required for practical Citation Network use.")
        _set_required_secret(config, "S2_API_KEY", "Semantic Scholar API key")

    if level != "llm":
        return
    print("\nChoose the default LLM provider:")
    print("   [1] DeepSeek V4 Pro API (recommended for batch processing)")
    print("   [2] Codex CLI (uses your local Codex login and quota)")
    print("   [3] Claude CLI (uses your local Claude login and quota)")
    print("   [4] OpenAI-compatible server (Ollama, LM Studio, vLLM, etc.)")
    provider = input("Select [1-4, default is 1]: ").strip() or "1"
    if provider == "2":
        config.update({
            "LLM_DEFAULT": "codex_cli:auto", "LLM_EXPAND": "codex_cli:auto",
            "LLM_SUMMARY": "codex_cli:auto", "LLM_EXTRACT": "codex_cli:auto",
        })
    elif provider == "3":
        config.update({
            "LLM_DEFAULT": "claude_cli:auto", "LLM_EXPAND": "claude_cli:auto",
            "LLM_SUMMARY": "claude_cli:auto", "LLM_EXTRACT": "claude_cli:auto",
        })
    elif provider == "4":
        config.update({
            "LLM_DEFAULT": "openai_compat:local", "LLM_EXPAND": "openai_compat:local",
            "LLM_SUMMARY": "openai_compat:local", "LLM_EXTRACT": "openai_compat:local",
        })
        base = input("OpenAI-compatible base URL [http://localhost:11434/v1]: ").strip()
        config["LLM_OPENAI_BASE_URL"] = base or "http://localhost:11434/v1"
        _set_optional_secret(config, "LLM_OPENAI_API_KEY", "API key if required")
    else:
        config.update({
            "LLM_DEFAULT": "deepseek:deepseek-v4-pro",
            "LLM_EXPAND": "deepseek:deepseek-v4-pro",
            "LLM_SUMMARY": "deepseek:deepseek-v4-pro",
            "LLM_EXTRACT": "deepseek:deepseek-v4-pro",
        })
        _set_optional_secret(config, "DEEPSEEK_API_KEY", "DeepSeek API key")

    print("\nChoose what may be sent to a cloud LLM:")
    print("   [1] Exclude tagged items (recommended)")
    print("   [2] Allow all Zotero items")
    print("   [3] Keep cloud processing disabled until configured manually")
    policy = input("Select [1-3, default is 1]: ").strip() or "1"
    if policy == "2":
        config["SUMMARY_ALLOW_CLOUD_ALL"] = "1"
        config["EXTRACT_ALLOW_CLOUD_ALL"] = "1"
        config.pop("SUMMARY_EXCLUDE_TAGS", None)
        config.pop("EXTRACT_EXCLUDE_TAGS", None)
    elif policy == "3":
        for key in (
            "SUMMARY_ALLOW_CLOUD_ALL", "EXTRACT_ALLOW_CLOUD_ALL",
            "SUMMARY_EXCLUDE_TAGS", "EXTRACT_EXCLUDE_TAGS",
        ):
            config.pop(key, None)
    else:
        default_tags = config.get("EXTRACT_EXCLUDE_TAGS", "private,confidential")
        tags = input(f"Excluded Zotero tags [{default_tags}]: ").strip() or default_tags
        config["SUMMARY_EXCLUDE_TAGS"] = tags
        config["EXTRACT_EXCLUDE_TAGS"] = tags
        config.pop("SUMMARY_ALLOW_CLOUD_ALL", None)
        config.pop("EXTRACT_ALLOW_CLOUD_ALL", None)


def print_configuration_status(config: dict[str, str]) -> None:
    level = config.get("FEATURE_LEVEL", "legacy/custom")
    print("Zotero Local RAG configuration")
    print(f"  level          : {level}")
    print(f"  Zotero data    : {config.get('ZOTERO_DATA_DIR', '~/Zotero')}")
    print(f"  embedding      : {config.get('EMB_PROFILE', 'fast')}")
    print(f"  S2 API key     : {'configured' if config.get('S2_API_KEY') else 'missing'}")
    print(f"  default LLM    : {config.get('LLM_DEFAULT', 'not configured')}")
    if config.get("SUMMARY_EXCLUDE_TAGS") or config.get("EXTRACT_EXCLUDE_TAGS"):
        policy = "tag blacklist"
    elif config.get("SUMMARY_ALLOW_CLOUD_ALL") == "1" or config.get("EXTRACT_ALLOW_CLOUD_ALL") == "1":
        policy = "allow all"
    else:
        policy = "fail-closed"
    print(f"  cloud policy   : {policy}")


def get_claude_config_path() -> Path | None:
    system = platform.system()
    if system == "Darwin":
        return Path.home() / "Library" / "Application Support" / "Claude" / "claude_desktop_config.json"
    elif system == "Windows":
        appdata = os.environ.get("APPDATA", "")
        if appdata:
            return Path(appdata) / "Claude" / "claude_desktop_config.json"
    elif system == "Linux":
        return Path.home() / ".config" / "Claude" / "claude_desktop_config.json"
    return None


def configure_claude_mcp(root_dir: Path, chroma_dir: Path, emb_profile: str,
                         env_overrides: dict | None = None) -> bool:
    config_path = get_claude_config_path()
    if config_path is None:
        print("[!] Unsupported OS — could not determine Claude config path. Skipping MCP setup.")
        return False

    uv_path = shutil.which("uv") or str(Path.home() / ".local" / "bin" / "uv")

    new_entry = {
        "command": uv_path,
        "args": [
            "--directory",
            str(root_dir),
            "run",
            "python",
            "-u",
            "src/rag_mcp_server.py",
        ],
        "env": {
            "CHROMA_DIR": str(chroma_dir),
            "EMB_PROFILE": emb_profile,
        },
    }
    if env_overrides:
        new_entry["env"].update(env_overrides)

    if config_path.exists():
        try:
            with open(config_path, "r", encoding="utf-8") as f:
                config = json.load(f)
        except json.JSONDecodeError:
            print(f"[!] Could not parse {config_path}. Skipping MCP setup.")
            return False
    else:
        config_path.parent.mkdir(parents=True, exist_ok=True)
        config = {}

    config.setdefault("mcpServers", {})

    existing = config["mcpServers"].get("zotero-rag")
    if existing:
        print(f"\n[Current MCP config for zotero-rag]")
        print(f"  command : {existing.get('command')}")
        print(f"  args    : {existing.get('args')}")
        ans = input("MCP config already exists. Overwrite? [y/N]: ").strip().lower()
        if ans != "y":
            print("Skipped MCP config update.")
            return False

    config["mcpServers"]["zotero-rag"] = new_entry

    with open(config_path, "w", encoding="utf-8") as f:
        json.dump(config, f, indent=2, ensure_ascii=False)

    print(f"\n[+] Claude MCP config updated: {config_path}")
    print(f"    command : {uv_path}")
    print(f"    args    : {new_entry['args']}")
    return True


def main(argv: list[str] | None = None):
    parser = argparse.ArgumentParser(description="Configure Zotero Local RAG.")
    parser.add_argument(
        "--status", action="store_true",
        help="show the effective feature configuration without revealing secrets",
    )
    args = parser.parse_args(argv)
    root_dir = Path(__file__).resolve().parents[1]
    env_path = root_dir / ".env"

    existing_config = read_env_file(env_path)
    if args.status:
        policy_config = read_env_file(root_dir / ".env.policy")
        print_configuration_status({**policy_config, **existing_config})
        return

    print("=" * 60)
    print("   Zotero Local RAG - Setup & Indexer")
    print("=" * 60)

    modify = True
    prev_emb_profile = existing_config.get("EMB_PROFILE", "fast")
    if "ZOTERO_DATA_DIR" in existing_config:
        print("\n[Current Configuration]")
        print(f"  ZOTERO_DATA_DIR : {existing_config['ZOTERO_DATA_DIR']}")
        print(f"  EMB_PROFILE     : {prev_emb_profile}")
        print(f"  FEATURE_LEVEL   : {existing_config.get('FEATURE_LEVEL', 'legacy/custom')}")
        print(f"  S2_API_KEY      : {'configured' if existing_config.get('S2_API_KEY') else 'not configured'}")
        print(f"  LLM             : {existing_config.get('LLM_DEFAULT', 'not configured')}")
        ans = input("\nExisting settings found. Do you want to change them? [y/N]: ").strip().lower()
        if ans != "y":
            modify = False

    if modify:
        default_zotero = os.path.expanduser("~/Zotero")
        if os.name == "nt":
            default_zotero = os.path.expanduser(r"~\Zotero")

        zotero_dir = input(
            f"\n1. Where is your Zotero data directory?\n   (Press Enter for default: {default_zotero})\n> "
        ).strip()
        if not zotero_dir:
            zotero_dir = default_zotero
        existing_config["ZOTERO_DATA_DIR"] = zotero_dir

        print("\n2. Which Embedding Model Profile do you want to use?")
        print("   [1] fast (Default, smaller/faster, good for standard text)")
        print("   [2] bge  (BGE-M3, heavier, supports extensive multilingual text)")
        emb_choice = input("Select [1 or 2, default is 1]: ").strip()

        if emb_choice == "2":
            existing_config["EMB_PROFILE"] = "bge"
        else:
            existing_config["EMB_PROFILE"] = "fast"

        configure_feature_level(existing_config)
        write_env_file(env_path, existing_config)
        print("\n[+] Configuration successfully saved to .env")

    emb_profile = existing_config.get("EMB_PROFILE", "fast")
    profile_changed = modify and emb_profile != prev_emb_profile
    chroma_dir = Path(existing_config.get("CHROMA_DIR", str(root_dir / "data" / "chroma")))

    print("\n" + "=" * 60)
    print("4. Configure Claude Desktop MCP server")
    ans = input("Register zotero-rag in Claude Desktop's MCP config? [y/N]: ").strip().lower()
    if ans == "y":
        configure_claude_mcp(root_dir, chroma_dir, emb_profile)
    else:
        print("\nSkipped MCP config.")
        print("To set up manually, add the following to claude_desktop_config.json:")
        uv_path = shutil.which("uv") or "uv"
        manual_env = {
            "CHROMA_DIR": str(chroma_dir),
            "EMB_PROFILE": emb_profile,
        }
        manual = {
            "zotero-rag": {
                "command": uv_path,
                "args": [
                    "--directory",
                    str(root_dir),
                    "run",
                    "python",
                    "-u",
                    "src/rag_mcp_server.py",
                ],
                "env": manual_env,
            }
        }
        print(json.dumps(manual, indent=2))

    # Check for Tesseract OCR (optional, improves Japanese PDF extraction)
    print("\n" + "=" * 60)
    print("5. Tesseract OCR (optional, improves Japanese PDF text extraction)")
    tesseract_bin = shutil.which("tesseract")
    if not tesseract_bin:
        # Homebrew on Apple Silicon installs to /opt/homebrew/bin,
        # which may not be on PATH when invoked via uv run.
        for candidate in ["/opt/homebrew/bin/tesseract", "/usr/local/bin/tesseract"]:
            if Path(candidate).exists():
                tesseract_bin = candidate
                break

    tesseract_ok = False
    tesseract_jpn = False
    if tesseract_bin:
        try:
            result = subprocess.run(
                [tesseract_bin, "--list-langs"], capture_output=True, text=True, timeout=5
            )
            installed = set(
                line.strip() for line in result.stdout.splitlines()
                if line.strip() and not line.startswith("List")
            )
            if "eng" in installed:
                tesseract_ok = True
            if "jpn" in installed:
                tesseract_jpn = True
        except Exception:
            pass

    if tesseract_jpn:
        print("   ✅ Tesseract with Japanese support detected.")
        print("      OCR fallback is ready for Japanese PDFs.")
    elif tesseract_ok:
        print("   ⚠️  Tesseract found but Japanese language data is missing.")
        print("      Extraction failures in Japanese PDFs will use English OCR,")
        print("      which may produce garbled results.")
        print("      Install: brew install tesseract-lang")
    else:
        print("   ℹ️  Tesseract not found. OCR fallback will be unavailable.")
        print("      Japanese PDFs with custom fonts may produce garbled text.")
        print("      Install: brew install tesseract tesseract-lang")

    do_rebuild = False
    if profile_changed:
        print("\n" + "=" * 60)
        print("   ⚠️  Embedding model profile changed!")
        print(f"   Previous: {prev_emb_profile} → Current: {emb_profile}")
        print()
        print("   Different embedding models produce vectors of different")
        print("   dimensions. A new ChromaDB collection will be created")
        print("   automatically (e.g., zotero_paragraphs_384 → zotero_paragraphs_1024).")
        print()
        print("   The OLD collection will remain on disk and consume space.")
        ans = input("   Delete old ChromaDB and rebuild from scratch? [y/N]: ").strip().lower()
        if ans == "y":
            do_rebuild = True

    print("\n" + "=" * 60)
    if do_rebuild:
        run_idx = "y"
        print("Will rebuild ChromaDB from scratch.")
    else:
        run_idx = input("Do you want to run the Embedding Indexer now? (Y/n): ").strip().lower()

    if run_idx != "n":
        print("\n[+] Starting Embedding process (this may download models if first time)...")
        print("[+] This process reads your Zotero local database and vectorizes PDFs/HTMLs.\n")

        env = os.environ.copy()
        env.update(existing_config)

        args = ["uv", "run", "src/index_from_zotero.py", "--progress"]
        if do_rebuild:
            args.append("--rebuild")

        process = subprocess.run(args, env=env, cwd=root_dir)

        if process.returncode == 0:
            print("\n[+] Indexing completed successfully!")
        else:
            print(f"\n[!] Indexing failed with exit code {process.returncode}.")
    else:
        print("\nSkipped indexing.")

    print("\nSetup wizard finished.")
    print(f"Configured level: {existing_config.get('FEATURE_LEVEL', 'legacy/custom')}")
    print("Run Setup.command again at any time to change or extend the configuration.")
    print("You can close this window.")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n[!] Setup aborted by user.")
