#!/usr/bin/env python3
import argparse
import json
import getpass
import os
import platform
from contextlib import contextmanager
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src.v3_data_plane import (
    V3_COLLECTION, V3_LEXICAL_NAME, V3_MANIFEST_NAME,
)

ENV_GROUPS = (
    ("Core: local search and indexing", (
        "FEATURE_LEVEL", "ZOTERO_DATA_DIR", "CHROMA_DIR", "EMB_PROFILE",
        "EMB_MODEL", "EMB_DEVICE", "HF_HUB_OFFLINE", "TRANSFORMERS_OFFLINE",
        "INGEST_STRUCTURED_V3_ENABLE", "HIERARCHICAL_SEARCH_V2_ENABLE",
        "CHROMA_COLLECTION", "MANIFEST_PATH", "LEXICAL_DB_PATH",
    )),
    ("Citation network and bibliographic metadata", (
        "S2_API_KEY", "ZOTERO_USER_ID", "ZOTERO_API_KEY", "CINII_APP_ID",
        "CROSSREF_MAILTO",
    )),
    ("LLM-assisted features", (
        "LLM_CHEAP", "LLM_STANDARD", "LLM_REVIEW",
        "DEEPSEEK_API_KEY", "DEEPSEEK_THINKING", "DEEPSEEK_REASONING_EFFORT",
        "ANTHROPIC_API_KEY", "LLM_OPENAI_BASE_URL", "LLM_OPENAI_API_KEY",
        "SUMMARY_EXCLUDE_TAGS", "EXTRACT_EXCLUDE_TAGS",
        "SUMMARY_ALLOW_CLOUD_ALL", "EXTRACT_ALLOW_CLOUD_ALL",
        "SUMMARY_BATCH_MAX_ITEMS", "SUMMARY_BATCH_WORKERS",
    )),
)


def read_env_file(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if "=" in stripped and not stripped.startswith("#"):
            key, value = stripped.split("=", 1)
            values[key.strip()] = value.strip()
    return values


def write_env_file(path: Path, values: dict[str, str]) -> None:
    """Write a predictable, grouped .env while preserving unknown settings."""
    rendered = [
        "# Generated by scripts/setup_wizard.py.",
        "# Secrets stay local: .env is excluded from Git.",
    ]
    written: set[str] = set()
    for title, keys in ENV_GROUPS:
        rows = [f"{key}={values[key]}" for key in keys if values.get(key, "") != ""]
        if rows:
            rendered.extend(["", f"# {title}", *rows])
            written.update(key for key in keys if values.get(key, "") != "")
    extras = sorted(
        key for key, value in values.items() if key not in written and value != ""
    )
    if extras:
        rendered.extend(["", "# Other existing settings"])
        rendered.extend(f"{key}={values[key]}" for key in extras)
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(path.name + ".tmp")
    temporary.write_text("\n".join(rendered) + "\n", encoding="utf-8")
    try:
        temporary.chmod(0o600)
    except OSError:
        pass
    temporary.replace(path)


def _set_optional_secret(config: dict[str, str], key: str, prompt: str) -> None:
    current = bool(config.get(key))
    suffix = " [configured; Enter keeps it, '-' removes it]" if current else " [optional]"
    value = getpass.getpass(prompt + suffix + ": ").strip()
    if value == "-":
        config.pop(key, None)
    elif value:
        config[key] = value


def _set_required_secret(config: dict[str, str], key: str, prompt: str) -> None:
    """Require a secret while allowing Enter to retain an existing value."""
    while True:
        current = bool(config.get(key))
        suffix = " [configured; Enter keeps it]" if current else " [required]"
        value = getpass.getpass(prompt + suffix + ": ").strip()
        if value:
            config[key] = value
            return
        if current:
            return
        print(f"{key} is required for the selected feature. Please enter a value.")


#: The three axes of note 80 are independent, so a preset is only a set of
#: defaults for them -- not a mode the rest of the system knows about.
V3_DATA_PLANE = {
    "INGEST_STRUCTURED_V3_ENABLE": "1",
    "HIERARCHICAL_SEARCH_V2_ENABLE": "1",
    "CHROMA_COLLECTION": V3_COLLECTION,
    "MANIFEST_PATH": f"data/{V3_MANIFEST_NAME}",
    "LEXICAL_DB_PATH": f"data/{V3_LEXICAL_NAME}",
}


PRESETS: dict[str, dict[str, str]] = {
    "minimal": {
        **V3_DATA_PLANE,
        "FEATURE_LEVEL": "core",
        "PDF_STRUCTURE_RECOVERY_ENABLE": "0",
        "PDF_AI_TOC_FAST_PATH_ENABLE": "0",
        "OCR_LAYER_AUDIT_ENABLE": "0",
        "QUERY_EXPANSION_ENABLE": "0",
        "LLM_SUMMARIES_ENABLE": "0",
        "LLM_REFERENCE_EXTRACTION_ENABLE": "0",
        "PDF_MISTRAL_TOC_QUEUE_ENABLE": "0",
        "CITATION_NETWORK_ENABLE": "0",
    },
    "local": {
        **V3_DATA_PLANE,
        "FEATURE_LEVEL": "citation",
        "PDF_STRUCTURE_RECOVERY_ENABLE": "1",
        "PDF_STRUCTURE_ENGINE_SHORT": "docling",
        "PDF_STRUCTURE_ENGINE_LONG": "docling",
        "PDF_AI_TOC_FAST_PATH_ENABLE": "0",
        "OCR_LAYER_AUDIT_ENABLE": "0",
        "QUERY_EXPANSION_ENABLE": "0",
        "LLM_SUMMARIES_ENABLE": "0",
        "LLM_REFERENCE_EXTRACTION_ENABLE": "0",
        "PDF_MISTRAL_TOC_QUEUE_ENABLE": "0",
        "CITATION_NETWORK_ENABLE": "1",
    },
    "full": {
        **V3_DATA_PLANE,
        "FEATURE_LEVEL": "llm",
        "PDF_STRUCTURE_RECOVERY_ENABLE": "1",
        "PDF_STRUCTURE_ENGINE_SHORT": "docling",
        "PDF_STRUCTURE_ENGINE_LONG": "mistral",
        "PDF_AI_TOC_FAST_PATH_ENABLE": "1",
        "OCR_LAYER_AUDIT_ENABLE": "1",
        "QUERY_EXPANSION_ENABLE": "1",
        "LLM_SUMMARIES_ENABLE": "1",
        "LLM_REFERENCE_EXTRACTION_ENABLE": "1",
        "PDF_MISTRAL_TOC_QUEUE_ENABLE": "1",
        "CITATION_NETWORK_ENABLE": "1",
    },
}

LLM_FLAGS = (
    "PDF_AI_TOC_FAST_PATH_ENABLE", "OCR_LAYER_AUDIT_ENABLE", "QUERY_EXPANSION_ENABLE",
    "LLM_SUMMARIES_ENABLE", "LLM_REFERENCE_EXTRACTION_ENABLE",
)


def describe_preset(config: dict[str, str]) -> str:
    """Name the preset the current configuration matches, if any."""
    for name, values in PRESETS.items():
        if all(config.get(key) == value for key, value in values.items()):
            return name
    return "custom"


def apply_preset(config: dict[str, str], name: str) -> None:
    config.update(PRESETS[name])


def enforce_v3_configuration(config: dict[str, str]) -> None:
    """Migrate edited configuration to the sole supported production data plane."""
    config.update(V3_DATA_PLANE)


def _granite_selectable() -> bool:
    try:
        from src.feature_gates import granite_configured
    except ImportError:  # pragma: no cover - src not importable in odd layouts
        return False
    return granite_configured()


def _choose_engine(label: str, current: str) -> str:
    """Choice (C) for one size bucket.

    The three options are presented with their trade-offs rather than a
    recommendation, because which one is right depends on what the library
    holds and whether the owner will pay per page.
    """
    options = [
        ("docling", "Docling — free, fast, best on tables and formulas"),
        ("mistral", "Mistral OCR — paid per page, fast, strongest on long scans"),
    ]
    if _granite_selectable():
        options.insert(1, ("granite", "Granite — free, ~2.3x slower, more accurate overall"))
    print(f"\n  {label}")
    for number, (_name, description) in enumerate(options, start=1):
        print(f"     [{number}] {description}")
    if not any(name == "granite" for name, _description in options):
        print("     (Granite needs its own virtualenv; see dev-notes 68 to enable it)")
    names = [name for name, _description in options]
    default = str(names.index(current) + 1) if current in names else "1"
    choice = input(f"  Select [1-{len(options)}, default is {default}]: ").strip() or default
    try:
        return options[int(choice) - 1][0]
    except (ValueError, IndexError):
        return options[0][0]


def configure_pdf_engines(config: dict[str, str]) -> None:
    boundary = config.get("PDF_STRUCTURE_ENGINE_PAGE_BOUNDARY", "30")
    print(f"\nWhich engine should structure PDFs? (split at {boundary} pages)")
    config["PDF_STRUCTURE_ENGINE_SHORT"] = _choose_engine(
        f"Shorter than {boundary} pages:", config.get("PDF_STRUCTURE_ENGINE_SHORT", "docling"),
    )
    config["PDF_STRUCTURE_ENGINE_LONG"] = _choose_engine(
        f"{boundary} pages or more:", config.get("PDF_STRUCTURE_ENGINE_LONG", "docling"),
    )
    entered = input(f"\n  Page boundary [{boundary}]: ").strip()
    if entered.isdigit() and int(entered) > 0:
        config["PDF_STRUCTURE_ENGINE_PAGE_BOUNDARY"] = entered
    uses_mistral = "mistral" in {
        config["PDF_STRUCTURE_ENGINE_SHORT"], config["PDF_STRUCTURE_ENGINE_LONG"],
    }
    config["PDF_MISTRAL_TOC_QUEUE_ENABLE"] = "1" if uses_mistral else "0"
    if uses_mistral:
        _set_required_secret(config, "MISTRAL_OCR_API_KEY", "Mistral OCR API key")


def configure_llm_provider(config: dict[str, str]) -> None:
    print("\nChoose the default LLM provider:")
    print("   [1] DeepSeek API: Flash / Pro / Pro (recommended)")
    print("   [2] Codex CLI (uses your local Codex login and quota)")
    print("   [3] Claude CLI (uses your local Claude login and quota)")
    print("   [4] OpenAI-compatible server (Ollama, LM Studio, vLLM, etc.)")
    provider = input("Select [1-4, default is 1]: ").strip() or "1"
    for legacy_key in ("LLM_DEFAULT", "LLM_EXPAND", "LLM_SUMMARY", "LLM_EXTRACT"):
        config.pop(legacy_key, None)
    if provider == "2":
        config.update(dict.fromkeys(
            ("LLM_CHEAP", "LLM_STANDARD", "LLM_REVIEW"), "codex_cli:auto"))
    elif provider == "3":
        config.update(dict.fromkeys(
            ("LLM_CHEAP", "LLM_STANDARD", "LLM_REVIEW"), "claude_cli:auto"))
    elif provider == "4":
        config.update(dict.fromkeys(
            ("LLM_CHEAP", "LLM_STANDARD", "LLM_REVIEW"), "openai_compat:local"))
        base = input("OpenAI-compatible base URL [http://localhost:11434/v1]: ").strip()
        config["LLM_OPENAI_BASE_URL"] = base or "http://localhost:11434/v1"
        _set_optional_secret(config, "LLM_OPENAI_API_KEY", "API key if required")
    else:
        config.update({
            "LLM_CHEAP": "deepseek:deepseek-v4-flash",
            "LLM_STANDARD": "deepseek:deepseek-v4-pro",
            "LLM_REVIEW": "deepseek:deepseek-v4-pro",
        })
        _set_required_secret(config, "DEEPSEEK_API_KEY", "DeepSeek API key")


def configure_feature_level(config: dict[str, str]) -> None:
    """Pick a preset, then optionally adjust the three axes individually."""
    # Settings removed on 2026-07-27: an item-level cloud veto could not hold,
    # since anything indexed reaches the assistant through search.
    for key in (
        "SUMMARY_ALLOW_CLOUD_ALL", "EXTRACT_ALLOW_CLOUD_ALL",
        "SUMMARY_EXCLUDE_TAGS", "EXTRACT_EXCLUDE_TAGS",
        "OCR_FALLBACK_ALLOW_CLOUD_ALL", "OCR_FALLBACK_EXCLUDE_TAGS",
        "MISTRAL_OCR_FALLBACK_ENABLE",
    ):
        config.pop(key, None)

    existing = describe_preset(config)
    print("\n3. How should this installation be set up?")
    print("   [1] Minimal — nothing to obtain, no charges. PDFs indexed as plain text")
    print("   [2] Local — no charges. PDF structuring with Docling; free S2 key recommended")
    print("   [3] Full — charged. Adds AI TOC, hierarchical summaries, Mistral OCR for long scans")
    can_keep = "FEATURE_LEVEL" in config or any(flag in config for flag in LLM_FLAGS)
    if can_keep:
        print(f"   [0] Keep the current settings (currently: {existing})")
    default = "0" if can_keep and existing == "custom" else {
        "minimal": "1", "local": "2", "full": "3",
    }.get(existing, "1")
    choice = input(f"Select [0-3, default is {default}]: ").strip() or default
    if choice == "0":
        return
    name = {"2": "local", "3": "full"}.get(choice, "minimal")
    apply_preset(config, name)

    if name != "minimal":
        print("\nA Semantic Scholar API key is free, but the unkeyed public rate")
        print("limit is too low for the Citation Network to make progress.")
        _set_optional_secret(config, "S2_API_KEY", "Semantic Scholar API key")
        if not config.get("S2_API_KEY"):
            config["CITATION_NETWORK_ENABLE"] = "0"
            config["FEATURE_LEVEL"] = "core" if name == "local" else "llm"
    if name == "full":
        configure_llm_provider(config)
        _set_optional_secret(config, "MISTRAL_OCR_API_KEY", "Mistral OCR API key")
        if not config.get("MISTRAL_OCR_API_KEY"):
            # Rather than leaving a setting that would stop the next run.
            config["PDF_STRUCTURE_ENGINE_LONG"] = "docling"
            config["PDF_MISTRAL_TOC_QUEUE_ENABLE"] = "0"

    if config.get("PDF_STRUCTURE_RECOVERY_ENABLE") == "1":
        answer = input("\nAdjust which engine structures PDFs? [y/N]: ").strip().lower()
        if answer in {"y", "yes"}:
            configure_pdf_engines(config)


def print_configuration_status(config: dict[str, str]) -> None:
    level = config.get("FEATURE_LEVEL", "legacy/custom")
    print("Zotero Local RAG configuration")
    print(f"  level          : {level}")
    print(f"  Zotero data    : {config.get('ZOTERO_DATA_DIR', '~/Zotero')}")
    print(f"  embedding      : {config.get('EMB_PROFILE', 'fast')}")
    print(f"  S2 API key     : {'configured' if config.get('S2_API_KEY') else 'missing'}")
    print(f"  cheap LLM      : {config.get('LLM_CHEAP', 'not configured')}")
    print(f"  standard LLM   : {config.get('LLM_STANDARD', 'not configured')}")
    print(f"  review LLM     : {config.get('LLM_REVIEW', 'not configured')}")
    print(f"  preset         : {describe_preset(config)}")
    print(f"  data plane     : {config.get('CHROMA_COLLECTION', 'not configured')}")
    if config.get("PDF_STRUCTURE_RECOVERY_ENABLE") == "1":
        boundary = config.get("PDF_STRUCTURE_ENGINE_PAGE_BOUNDARY", "30")
        print(
            f"  PDF structure  : <{boundary}p "
            f"{config.get('PDF_STRUCTURE_ENGINE_SHORT', 'docling')} / "
            f">={boundary}p {config.get('PDF_STRUCTURE_ENGINE_LONG', 'docling')}"
        )
    else:
        print("  PDF structure  : off (indexed as plain text)")
    enabled = [flag for flag in LLM_FLAGS if config.get(flag) == "1"]
    print(f"  LLM features   : {len(enabled)}/{len(LLM_FLAGS)} enabled")
    # Report a feature switched on without its resource here too, so the
    # mismatch is visible at setup rather than only when a run refuses to start.
    for problem in _configuration_problems(config):
        print(f"  [!] {problem}")


def _configuration_problems(config: dict[str, str]) -> list[str]:
    """Same check the pipeline runs at startup, evaluated against ``config``.

    The .env loader is suspended for the duration: the wizard is reporting on
    the configuration being *edited*, and letting the file on disk leak in
    would show a key the user has not saved yet -- or hide one they just
    removed.
    """
    problems = _v3_configuration_problems(config)
    try:
        from src import feature_gates
    except ImportError:  # pragma: no cover - src not importable in odd layouts
        return problems
    original_loader = feature_gates.load_dotenv_native
    feature_gates.load_dotenv_native = lambda *_a, **_k: None
    try:
        with mock_environment(config):
            return problems + feature_gates.verify_enabled_features()
    finally:
        feature_gates.load_dotenv_native = original_loader


def _v3_configuration_problems(config: dict[str, str]) -> list[str]:
    return [
        f"{key} must be {expected!r}; the legacy data plane is retired."
        for key, expected in V3_DATA_PLANE.items()
        if str(config.get(key) or "") != expected
    ]


@contextmanager
def mock_environment(config: dict[str, str]):
    """Evaluate feature gates against a config dict rather than the live env."""
    saved = dict(os.environ)
    try:
        os.environ.clear()
        os.environ.update({key: str(value) for key, value in config.items()})
        yield
    finally:
        os.environ.clear()
        os.environ.update(saved)


def get_claude_config_path() -> Path | None:
    system = platform.system()
    if system == "Darwin":
        return Path.home() / "Library" / "Application Support" / "Claude" / "claude_desktop_config.json"
    elif system == "Windows":
        appdata = os.environ.get("APPDATA", "")
        if appdata:
            return Path(appdata) / "Claude" / "claude_desktop_config.json"
    elif system == "Linux":
        return Path.home() / ".config" / "Claude" / "claude_desktop_config.json"
    return None


def configure_claude_mcp(root_dir: Path, chroma_dir: Path, emb_profile: str,
                         env_overrides: dict | None = None) -> bool:
    config_path = get_claude_config_path()
    if config_path is None:
        print("[!] Unsupported OS — could not determine Claude config path. Skipping MCP setup.")
        return False

    uv_path = shutil.which("uv") or str(Path.home() / ".local" / "bin" / "uv")

    new_entry = {
        "command": uv_path,
        "args": [
            "--directory",
            str(root_dir),
            "run",
            "python",
            "-u",
            "src/rag_mcp_server.py",
        ],
        "env": {
            "CHROMA_DIR": str(chroma_dir),
            "EMB_PROFILE": emb_profile,
        },
    }
    if env_overrides:
        new_entry["env"].update(env_overrides)

    if config_path.exists():
        try:
            with open(config_path, "r", encoding="utf-8") as f:
                config = json.load(f)
        except json.JSONDecodeError:
            print(f"[!] Could not parse {config_path}. Skipping MCP setup.")
            return False
    else:
        config_path.parent.mkdir(parents=True, exist_ok=True)
        config = {}

    config.setdefault("mcpServers", {})

    existing = config["mcpServers"].get("zotero-rag")
    if existing:
        print(f"\n[Current MCP config for zotero-rag]")
        print(f"  command : {existing.get('command')}")
        print(f"  args    : {existing.get('args')}")
        ans = input("MCP config already exists. Overwrite? [y/N]: ").strip().lower()
        if ans != "y":
            print("Skipped MCP config update.")
            return False

    config["mcpServers"]["zotero-rag"] = new_entry

    temporary = config_path.with_name(config_path.name + ".tmp")
    with open(temporary, "w", encoding="utf-8") as f:
        json.dump(config, f, indent=2, ensure_ascii=False)
    temporary.replace(config_path)

    print(f"\n[+] Claude MCP config updated: {config_path}")
    print(f"    command : {uv_path}")
    print(f"    args    : {new_entry['args']}")
    return True


def main(argv: list[str] | None = None):
    parser = argparse.ArgumentParser(description="Configure Zotero Local RAG.")
    parser.add_argument(
        "--status", action="store_true",
        help="show the effective feature configuration without revealing secrets",
    )
    parser.add_argument(
        "--server", action="store_true",
        help="configure a server without offering local Claude Desktop registration",
    )
    args = parser.parse_args(argv)
    root_dir = Path(__file__).resolve().parents[1]
    env_path = root_dir / ".env"

    existing_config = read_env_file(env_path)
    if args.status:
        policy_config = read_env_file(root_dir / ".env.policy")
        print_configuration_status({**policy_config, **existing_config})
        return

    print("=" * 60)
    print("   Zotero Local RAG - V3 Setup")
    print("=" * 60)

    modify = True
    prev_emb_profile = existing_config.get("EMB_PROFILE", "fast")
    if "ZOTERO_DATA_DIR" in existing_config:
        print("\n[Current Configuration]")
        print(f"  ZOTERO_DATA_DIR : {existing_config['ZOTERO_DATA_DIR']}")
        print(f"  EMB_PROFILE     : {prev_emb_profile}")
        print(f"  FEATURE_LEVEL   : {existing_config.get('FEATURE_LEVEL', 'legacy/custom')}")
        print(f"  S2_API_KEY      : {'configured' if existing_config.get('S2_API_KEY') else 'not configured'}")
        print(f"  LLM_STANDARD    : {existing_config.get('LLM_STANDARD', 'not configured')}")
        ans = input("\nExisting settings found. Do you want to change them? [y/N]: ").strip().lower()
        if ans != "y":
            modify = False

    if not modify:
        retired = _v3_configuration_problems(existing_config)
        if retired:
            rendered = "\n".join(f"  - {problem}" for problem in retired)
            raise SystemExit(
                "Existing settings still target the retired data plane. "
                "Run the wizard again and choose to change them:\n" + rendered
            )

    if modify:
        default_zotero = os.path.expanduser("~/Zotero")
        if os.name == "nt":
            default_zotero = os.path.expanduser(r"~\Zotero")
        current_zotero = existing_config.get("ZOTERO_DATA_DIR", default_zotero)

        zotero_dir = input(
            f"\n1. Where is your Zotero data directory?\n"
            f"   (Press Enter to keep: {current_zotero})\n> "
        ).strip()
        if not zotero_dir:
            zotero_dir = current_zotero
        expanded_zotero = Path(zotero_dir).expanduser()
        if not (
            expanded_zotero.is_dir()
            and (expanded_zotero / "zotero.sqlite").is_file()
            and (expanded_zotero / "storage").is_dir()
        ):
            raise SystemExit(
                f"Invalid Zotero data directory: {expanded_zotero}\n"
                "Expected zotero.sqlite and storage/. No settings were changed."
            )
        existing_config["ZOTERO_DATA_DIR"] = zotero_dir

        print("\n2. Which Embedding Model Profile do you want to use?")
        print("   [1] fast (Default, smaller/faster, good for standard text)")
        print("   [2] bge  (BGE-M3, heavier, supports extensive multilingual text)")
        current_emb = existing_config.get("EMB_PROFILE", "fast")
        emb_default = "2" if current_emb == "bge" else "1"
        emb_choice = input(
            f"Select [1 or 2, Enter keeps {current_emb}]: "
        ).strip() or emb_default

        if emb_choice == "2":
            existing_config["EMB_PROFILE"] = "bge"
        else:
            existing_config["EMB_PROFILE"] = "fast"

        configure_feature_level(existing_config)
        enforce_v3_configuration(existing_config)
        problems = _configuration_problems(existing_config)
        if problems:
            rendered = "\n".join(f"  - {problem}" for problem in problems)
            raise SystemExit(
                "Configuration is incomplete; no settings were saved:\n" + rendered
            )
        write_env_file(env_path, existing_config)
        print("\n[+] Configuration successfully saved to .env")

    emb_profile = existing_config.get("EMB_PROFILE", "fast")
    profile_changed = modify and emb_profile != prev_emb_profile
    chroma_dir = Path(existing_config.get("CHROMA_DIR", str(root_dir / "data" / "chroma")))

    if args.server:
        print("\n4. Server mode: skipped local Claude Desktop registration.")
    else:
        print("\n" + "=" * 60)
        print("4. Configure Claude Desktop MCP server")
        ans = input("Register zotero-rag in Claude Desktop's MCP config? [y/N]: ").strip().lower()
        if ans == "y":
            configure_claude_mcp(
                root_dir, chroma_dir, emb_profile, env_overrides=V3_DATA_PLANE,
            )
        else:
            print("\nSkipped MCP config.")
            print("To set up manually, add the following to claude_desktop_config.json:")
            uv_path = shutil.which("uv") or "uv"
            manual_env = {
                "CHROMA_DIR": str(chroma_dir),
                "EMB_PROFILE": emb_profile,
                **V3_DATA_PLANE,
            }
            manual = {
                "zotero-rag": {
                    "command": uv_path,
                    "args": [
                        "--directory",
                        str(root_dir),
                        "run",
                        "python",
                        "-u",
                        "src/rag_mcp_server.py",
                    ],
                    "env": manual_env,
                }
            }
            print(json.dumps(manual, indent=2))

    # Check for Tesseract OCR (optional, improves Japanese PDF extraction)
    print("\n" + "=" * 60)
    print("5. Tesseract OCR (optional, improves Japanese PDF text extraction)")
    tesseract_bin = shutil.which("tesseract")
    if not tesseract_bin:
        # Homebrew on Apple Silicon installs to /opt/homebrew/bin,
        # which may not be on PATH when invoked via uv run.
        for candidate in ["/opt/homebrew/bin/tesseract", "/usr/local/bin/tesseract"]:
            if Path(candidate).exists():
                tesseract_bin = candidate
                break

    tesseract_ok = False
    tesseract_jpn = False
    if tesseract_bin:
        try:
            result = subprocess.run(
                [tesseract_bin, "--list-langs"], capture_output=True, text=True, timeout=5
            )
            installed = set(
                line.strip() for line in result.stdout.splitlines()
                if line.strip() and not line.startswith("List")
            )
            if "eng" in installed:
                tesseract_ok = True
            if "jpn" in installed:
                tesseract_jpn = True
        except Exception:
            pass

    if tesseract_jpn:
        print("   ✅ Tesseract with Japanese support detected.")
        print("      OCR fallback is ready for Japanese PDFs.")
    elif tesseract_ok:
        print("   ⚠️  Tesseract found but Japanese language data is missing.")
        print("      Extraction failures in Japanese PDFs will use English OCR,")
        print("      which may produce garbled results.")
        print("      Install: brew install tesseract-lang")
    else:
        print("   ℹ️  Tesseract not found. OCR fallback will be unavailable.")
        print("      Japanese PDFs with custom fonts may produce garbled text.")
        print("      Install: brew install tesseract tesseract-lang")

    if profile_changed:
        print("\n" + "=" * 60)
        print("   ⚠️  Embedding model profile changed!")
        print(f"   Previous: {prev_emb_profile} → Current: {emb_profile}")
        print()
        print("   The V3 collection must be rebuilt before this profile can be used.")

    print("\nSetup wizard finished.")
    print(f"Configured level: {existing_config.get('FEATURE_LEVEL', 'legacy/custom')}")
    print("No database build or paid API operation was started by this wizard.")
    print("Next: run Server-Database-Workflow.command and complete phases 1 through 4.")
    print("Run Setup.command again at any time to change or extend the configuration.")
    print("You can close this window.")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n[!] Setup aborted by user.")
